#+title: A simple lisp micro-service 
#+author:  Spike Spiegel

* Introduction
The idea behind this project is to create and deploy a simple interface based on LISP on Kubernetes. Completely crazy? Probably ;-) 
The second idea is simply to convert my /go-video-api/ on LISP, so...
* Podman
Just to be true to myself, I'll use /podman/. Let's start the virtual machine.
#+begin_src shell
$ podman machime start
$ podman info
#+end_src
* Process
** Run
To test the application without stress, I created this smart script.
** Build Script explanation
Just an overview of the script to build the binary
** How to Build
To simplify the process, I proposed to build in the first step /yano-bin/ in order to push the image as simple as possible through a basic /Dockerfile/.
#+begin_src shell
$ sbcl --script build.lisp
#+end_src
* Image
** Dockerfile
I said previously that the best and lazy solution was to build in first the /binary/, so I stay on this inflexible position.
We don't forget to select the right architecture (Linux/AMD), hence the need to compile in a clean container and then create the image.
** Build
Pretty simple,
#+begin_src shell
$ podman build -t $(USER)/yano-bin:latest .
#+end_src
** Push
It's time to push our new image
#+begin_src shell
$ podman push $(USER)/yano-bin:latest 
#+end_src
Write your personal name ($USER) obviously. (ex: gandalfthewhite/yano-bin:latest, just for me)
* Micro-service
** Manifest
Actually, the /manifest/ is normal without any difference, we just have to select the right image.
** Deploy
